### ISSUE TITLE
Switch to using Google Analytics 4

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1295]
WhatDoTheyKnow's Google Analytics currently has the notice:

>Universal Analytics will no longer process new data in standard properties beginning 1 July 2023. Prepare now by setting up and switching over to a Google Analytics 4 property.

See: [Introducing Google Analytics 4 (GA4)](https://support.google.com/analytics/answer/10089681?hl=en)

We'll want to consider the privacy implications of any change and if necessary update [the privacy page section on Cookies and third party services](https://www.whatdotheyknow.com/help/privacy#cookies).

**Comment by mdeuk** [comment]
Linked ticket: https://github.com/mysociety/alaveteli/issues/6973

**Comment by gbp** [comment]
Done in https://github.com/mysociety/whatdotheyknow-theme/pull/1732 and https://github.com/mysociety/alaveteli/pull/7779

**Comment by garethrees** [comment]
After this migration the analytics interface was still showing an incomplete setup:

![Screenshot 2023-07-03 at 10 46 57](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/77bf274a-3358-480c-a773-cb61c3c2a84e)

I clicked through and the only item not marked as complete was "define audiences":

![Screenshot 2023-07-04 at 09 54 33](https://github.com/mysociety/whatdotheyknow-theme/assets/282788/d2b1fc37-3300-4e00-8aa2-f2af1d0461c4)

Clicking through to the details on that, we have some audiences defined:

<img width="1131" alt="Screenshot 2023-07-04 at 09 57 46" src="https://github.com/mysociety/whatdotheyknow-theme/assets/282788/0673efff-c67f-4b2e-a4d4-f83094fe798f">

IDK where these came from, but I don't think we were using them in any great detail before so this looks fine.

As such, I just clicked "mark as complete" and now the big red banner has gone away.

<img width="409" alt="Screenshot 2023-07-04 at 09 58 47" src="https://github.com/mysociety/whatdotheyknow-theme/assets/282788/9cff4548-1b46-43a0-877a-bd386184a107">

@ajparsons @MyfanwyNixon reopen this issue if there's something else we need to do here.
